import type { Metadata } from 'next';
import { Inter, Roboto_Mono } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';
import { TailwindIndicator } from '@/components/TailwindIndicator';
import Navbar from '@/components/nav/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const roboto = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto',
});

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head />
      <body className={cn('min-h-screen bg-background font-sans antialiased', inter.variable, roboto.variable)}>
        <main className=''>
          <Navbar />
          {children}
        </main>
        <TailwindIndicator />
      </body>
    </html>
  );
}
